
[[constraint]]
  name = "github.com/gengo/grpc-gateway"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "gopkg.in/russross/blackfriday.v2"
  version = "2.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
